# ===============================
# Spring Boot 通用配置
# ===============================
server:
  port: 8080
spring:
  config:
    import: "classpath:bill-web.yml"
  application:
    name: framework-test
  # 指定默认激活环境
  profiles:
    active: dev  # 可改为 dev/test/prod

mybatis-plus:
  #mapper-locations: classpath:/mapper/**/*.xml
  #type-aliases-package: com.bill.test.entity
  configuration:
    # 打印 SQL 日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-statement-timeout: 30 #流式查询超时
    default-result-set-type: FORWARD_ONLY #FORWARD_ONLY 是游标流式查询的关键，禁止随机访问，只允许向前遍历，避免一次性加载。
