# ===============================
# Spring Boot 通用配置
# ===============================
server:
  port: 8080
spring:
  config:
    import: "classpath:application-web.yml"
  application:
    name: framework-test
  # 指定默认激活环境
  profiles:
    active: dev  # 可改为 dev/test/prod

mybatis-plus:
  #mapper-locations: classpath:/mapper/**/*.xml
  #type-aliases-package: com.bill.test.entity
  configuration:
    # 打印 SQL 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
