#sa-token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: Authorization
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  is-read-cookie: false
  is-write-header: true
  # token风格
  token-style: tik
  # 是否输出操作日志
  is-log: false

#springdoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: bill
    operations-sorter: bill
  api-docs:
    path: /v3/api-docs

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: root
    password: 4396
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 接口文档
